# Generated by Django 4.1 on 2023-06-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ID",
                    models.CharField(default="abc", max_length=100, verbose_name="ID"),
                ),
                (
                    "PW",
                    models.CharField(default="abc", max_length=100, verbose_name="PW"),
                ),
            ],
        ),
    ]
