# Generated by Django 4.1 on 2023-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.RemoveField(model_name="post", name="created_date",),
        migrations.RemoveField(model_name="post", name="id",),
        migrations.RemoveField(model_name="post", name="published_date",),
        migrations.RemoveField(model_name="post", name="text",),
        migrations.RemoveField(model_name="post", name="title",),
        migrations.AddField(
            model_name="post",
            name="id_value",
            field=models.CharField(default="123", max_length=100, verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="post",
            name="key_value",
            field=models.FloatField(
                default=1687938135.869539,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="pw_value",
            field=models.CharField(default="adc", max_length=100, verbose_name="PW"),
        ),
    ]
