# Generated by Django 4.1 on 2023-06-28 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.RemoveField(model_name="post", name="created_date",),
        migrations.RemoveField(model_name="post", name="text",),
        migrations.RemoveField(model_name="post", name="title",),
        migrations.AddField(
            model_name="post",
            name="pw",
            field=models.CharField(default="", max_length=100, verbose_name="PW"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(default="", max_length=100, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, primary_key=True, serialize=False
            ),
        ),
    ]
