# Generated by Django 4.1 on 2023-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_author_remove_post_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="key_value",
            field=models.IntegerField(
                default=1687937559, primary_key=True, serialize=False
            ),
        ),
    ]
