# Generated by Django 4.1 on 2023-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_key_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="key_value",
            field=models.FloatField(
                primary_key=True, serialize=False, unique=True, verbose_name="key"
            ),
        ),
    ]
