# Generated by Django 4.1 on 2023-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_key_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="key_value",
            field=models.FloatField(
                default=1687939203.031774,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="key",
            ),
        ),
    ]
