# Generated by Django 4.1 on 2023-06-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_post_key_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id_value",
            field=models.CharField(
                default="123",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="key_value",
            field=models.FloatField(default=1687953883.23036, verbose_name="key"),
        ),
    ]
