# Generated by Django 4.1 on 2023-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_post_id_value_alter_post_key_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="key_value",
            field=models.FloatField(default=1687954013.929334, verbose_name="key"),
        ),
    ]
